<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\ChatDND.Core\ChatDND.Core.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyTitle>ChatDND</AssemblyTitle>
    <Product>ChatDND</Product>
    <Description>Windows 应用级免打扰工具</Description>
    <Company>ChatDND</Company>
    <Version>0.1.0</Version>
    <ApplicationIcon>Assets\ChatDND.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Assets\ChatDND.ico">
      <LogicalName>ChatDND.App.Assets.ChatDND.ico</LogicalName>
    </EmbeddedResource>
  </ItemGroup>

</Project>
